---
persistentVolume:
  storageCapacity: 50Gi
  claimStorageCapacity: 30Gi
  accessModes: ReadWriteMany
  localPath: /run/desktop/mnt/host/d/Work/Scripts/jenkins/JENKINS_HOME/
  mountPath: /var/jenkins_home
nodes:
  - docker-desktop
replicaCount: 1
image: 
  name: jenkins/jenkins:lts
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "1Gi"
    cpu: "500m"
port:
  containerPort: 
    httpport: 8080
    jnlpport: 50000
  servicePort: 80
  nodePort: 32000
serviceType: NodePort
ingress:
  path: /
  pathType: Prefix
  ingressClass: 
    name: nginx
