---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-admin
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-admin
  namespace: {{ .Chart.Name }}