apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-server
    spec:
      securityContext:
            # Note: fsGroup may be customized for a bit of better
            # filesystem security on the shared host
            fsGroup: 1000
            runAsUser: 1000
            ### runAsGroup: 1000
      serviceAccountName: {{ .Chart.Name }}-admin
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.name }}
          # OPTIONAL: check for new floating-tag LTS releases whenever the pod is restarted:
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
          ports:
            - name: httpport
              containerPort: {{ .Values.port.containerPort.httpport }}
            - name: jnlpport
              containerPort: {{ .Values.port.containerPort.jnlpport }}
          startupProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 600
            failureThreshold: 30 # Allows 5 minutes to start (30 * 10s)
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.port.containerPort.httpport }}
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: {{ .Values.port.containerPort.httpport }}
            initialDelaySeconds: 300
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: {{ .Chart.Name }}-data
              mountPath: {{ .Values.persistentVolume.mountPath }}
      volumes:
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pv-claim
          # hostPath:
          #   path: /run/desktop/mnt/host/d/Work/Scripts/jenkins/JENKINS_HOME/
          #   type: Directory
