apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Chart.Name }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector:
    app: {{ .Chart.Name }}-server
  type: {{ .Values.serviceType }}
  ports:
    - port: {{ .Values.port.containerPort.httpport }}
      targetPort: {{ .Values.port.servicePort }}
      nodePort: {{ .Values.port.nodePort }}